# Generated by Django 5.0.4 on 2024-05-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='Description',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Description',
            new_name='Descripcion',
        ),
    ]
