# Generated by Django 5.0.4 on 2024-05-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_description_artista_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='artistas'),
        ),
    ]
