# Generated by Django 5.0.4 on 2024-05-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_foro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='Nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='foro',
            name='Nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Nombre',
            field=models.CharField(max_length=50),
        ),
    ]
