# Generated by Django 5.0.4 on 2024-05-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_artista_nombre_alter_foro_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='Descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='foro',
            name='Descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Descripcion',
            field=models.CharField(max_length=1000),
        ),
    ]
