# Generated by Django 5.0.6 on 2024-05-14 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_artista_descripcion_alter_foro_descripcion_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="Price",
            new_name="Precio",
        ),
    ]
